/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spore_meitu_jni_ImageUtilEngine */

#ifndef _Included_com_spore_meitu_jni_ImageUtilEngine
#define _Included_com_spore_meitu_jni_ImageUtilEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spore_meitu_jni_ImageUtilEngine
 * Method:    getResultFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_spore_meitu_jni_ImageUtilEngine_getResultFromJni
  (JNIEnv *, jobject);

/*
 * Class:     com_spore_meitu_jni_ImageUtilEngine
 * Method:    toGray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_spore_meitu_jni_ImageUtilEngine_toGray
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_spore_meitu_jni_ImageUtilEngine
 * Method:    toFudiao
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_spore_meitu_jni_ImageUtilEngine_toFudiao
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_spore_meitu_jni_ImageUtilEngine
 * Method:    toHeibai
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_spore_meitu_jni_ImageUtilEngine_toHeibai
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_spore_meitu_jni_ImageUtilEngine
 * Method:    toMohu
 * Signature: ([IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_spore_meitu_jni_ImageUtilEngine_toMohu
  (JNIEnv *, jobject, jintArray, jint, jint, jint);

/*
 * Class:     com_spore_meitu_jni_ImageUtilEngine
 * Method:    toDipian
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_spore_meitu_jni_ImageUtilEngine_toDipian
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_spore_meitu_jni_ImageUtilEngine
 * Method:    toSunshine
 * Signature: ([IIIIIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_spore_meitu_jni_ImageUtilEngine_toSunshine
  (JNIEnv *, jobject, jintArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_spore_meitu_jni_ImageUtilEngine
 * Method:    toFangdajing
 * Signature: ([IIIIIIF)[I
 */
JNIEXPORT jintArray JNICALL Java_com_spore_meitu_jni_ImageUtilEngine_toFangdajing
  (JNIEnv *, jobject, jintArray, jint, jint, jint, jint, jint, jfloat);

/*
 * Class:     com_spore_meitu_jni_ImageUtilEngine
 * Method:    toHahajing
 * Signature: ([IIIIIIF)[I
 */
JNIEXPORT jintArray JNICALL Java_com_spore_meitu_jni_ImageUtilEngine_toHahajing
  (JNIEnv *, jobject, jintArray, jint, jint, jint, jint, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
