/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cam001_util_ImageUtil */

#ifndef _Included_com_cam001_util_ImageUtil
#define _Included_com_cam001_util_ImageUtil
#ifdef __cplusplus
extern "C" {
#endif
    
/*
 * Class:     com_cam001_util_ImageUtil
 * Method:    native_rotate
 * Signature: ([BIZZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_cam001_util_ImageUtil_native_1rotate
  (JNIEnv *, jclass, jbyteArray, jint, jboolean, jboolean);

/*
 * Class:     com_cam001_util_ImageUtil
 * Method:    native_enhance
 * Signature: ([BIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_cam001_util_ImageUtil_native_1enhance
  (JNIEnv *, jclass, jbyteArray, jfloatArray);
  
JNIEXPORT jbyteArray JNICALL Java_com_cam001_util_ImageUtil_native_1crop
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
